user:
  name:
    max_length: 50
  email:
    max_length: 50
  phone:
    max_length: 12
  date_of_birth:
    max_length: 10
  password:
    min_length: 6
  password:
    min_length: 6
  address:
    max_length: 255
cart:
  item_id_default: 1
  default_quantity: 1
name_max: 20
email_max: 255
pass_min: 6
user_per_page: 10
admin_layout: "admin"
app_layout: "application"
category_max: 30
description_max: 200
user_per_page: 10
cate_per_page: 10
category_max: 30
user_per_page: 10
product_per_page: 10
max_image_size: 1
cart_size: 1
min_size: 0
