name_max: 20
email_max: 255
phone_min: 10
phone_max: 15
pass_min: 6
user_per_page: 10
not_to_allow_less_1: 0
min_pass_length: 6
paginate:
  per_page: 9
  comment_perpage: 5
admin_layout: "admin"
app_layout: "application"
category_max: 30
description_max: 200
user_per_page: 10
cate_per_page: 10
quantity_min: 0
quantity_max: 500
product_min: 0
category_max: 30
user_per_page: 10
maximum_top_products: 8
product_per_page: 10
average_total: 0
min_quantity: 1
page: 1
max_image_size: 1
cart_size: 1
min_size: 0
image:
  size: "50x50"
product_title:
  length: 15
description:
  length: 20
quantity:
  default: 1
  zero: 0
comment:
  max_length: 500
statuses:
  cancelled: "cancelled"
  in_progress: "in_progress"
  rejected: "rejected"
  approved: "approved"
rating:
  point: !ruby/range 1..5
product:
  limit: 4
home:
  limit: 3
