name_max: 20
email_max: 255
pass_min: 6
user_per_page: 10
admin_layout: "admin"
app_layout: "application"
category_max: 30
description_max: 200
user_per_page: 10
cate_per_page: 10
category_max: 30
user_per_page: 10
product_per_page: 10
max_image_size: 1
cart_size: 1
min_size: 0
comment:
  min_length: 1
  max_length: 255
paginate:
  comment_perpage: 5
  product_perpage: 2
